<?php

$plugin = array(
  'title' => t('Technet 5-band 2col Head'),
  'icon' => 'technet-5-band.png',
  'category' => t('Technet Bootstrap'),
  'theme' => 'technet-5-band-2col-head',
  'css' => 'technet-5-band-2col-head.css',
  'regions' => array(
    'header-first' => t('Header First'),
    'header-last' => t('Header Last'),
    'row-1' => t('First row'),
    'row-2' => t('Second row'),
    'row-3' => t('Third row'),
    'footer' => t('Footer'),
  ),
);
