<?php

$plugin = array(
  'title' => t('Technet 33-66 stacked (well)'),
  'icon' => 'technet-33-66-stacked-well.png',
  'category' => t('Technet Bootstrap'),
  'theme' => 'technet-33-66-stacked-well',
  'css' => 'technet-33-66-stacked-well.css',
  'regions' => array(
    'header' => t('Header First'),
    'row-1-33-a' => t('Column 33-a'),
    'row-1-33-b' => t('Column 33-b'),
    'row-1-last' => t('Column 66'),
    'footer' => t('Footer'),
  ),
);
