<?php

$plugin = array(
  'title' => t('Technet product page'),
  'icon' => 'technet-product-page.png',
  'category' => t('Technet Bootstrap'),
  'theme' => 'technet-product-page',
  'css' => 'technet-product-page.css',
  'regions' => array(
    'header' => t('Header'),
    'row-1-first' => t('Column 75'),
    'row-1-last' => t('Column 25'),
    'row-2-first' => t('Column 25'),
    'row-2-last' => t('Column 75'),
    'footer' => t('Footer'),
  ),
);
