<?php
/**
 * @file
 * document_manager_groups.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function document_manager_groups_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_time_zone'
  $field_bases['field_time_zone'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_time_zone',
    'foreign keys' => array(),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'tzfield',
    'settings' => array(
      'exclude' => array(),
    ),
    'translatable' => 0,
    'type' => 'tzfield',
  );

  // Exported field_base: 'group_group'
  $field_bases['group_group'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'group_group',
    'foreign keys' => array(),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        0 => 'Not a group',
        1 => 'Group',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_boolean',
  );

  return $field_bases;
}
