<?php

/**
 * File: technet_feeds.module
 */

/**
 * Implements hook_rules_action_info
 *
 */
function technet_feeds_rules_action_info() {
    $actions = array(
	'technet_feeds_presave_action' => array(
	'label' => t('Set author of feeds-imported node to current author'),
	'group' => t('Technet Feeds'),
	'parameter' => array(
	    'node' => array(
		'type' => 'node',
		'label' => t('Imported node to save')
		),
	    ),
	),
    );
    return $actions;
}

function technet_feeds_presave_action($entity) {
   // take some action here
}

/**
 * Implements hook_feeds_before_update
 *
 */
function technet_feeds_feeds_presave(FeedsSource $source, $entity, $item) {
    // Reset the drupal node author to the UID of the current user (i.e., the one doing the import).
    global $user;
    $entity->uid = $user->uid;
}

/**
 * Implements hook_feeds_after_import
 */
function technet_feeds_feeds_after_import(FeedsSource $source) {
    // This hook seems to get invoked from inside the batch, so redirects here cause a catastrophic batch error.
    // drupal_goto('/'); // Causes AJAX error (attempts to feed page HTML into batch engine)
    
    // Provide link to publish page in message area until this is resolved.
    drupal_set_message('New imported content must be reviewed and published before it is available. Go to ' .
		       l("Edit and Publish External Resources", 'import/external_resource_importer/publish') .
		       ' to proceed. You can also bookmark this link and return later.', 'warning');
}

function technet_feeds_feeds_after_clear(FeedsSource $source) {
    // This does not get fired in current implementation; why? Possible alternative to using hook_fees_after_import?
}

